### ISSUE TITLE
help for dataset

### ISSUE THREAD

**Issue by Afindor** [pablosistemas/tpfinal-sistemasrecomendadao#1]
Hello I am also this research topic. Do you have fllowing data sets? Can you share them with me, Thank you.

'/data/datasets/'
'/data/ratings/'
 '/data/in_cluto/'
 '/data/in_slim/'
'jester-data-1.csv'

**Comment by pablosistemas** [comment]
@Afindor, I have uploaded some datasets as well as some explanations to getting started. Feel free to ask for more explanations. As long as I would getting time, I will provide more tutorials to help.

**Comment by Afindor** [comment]
@pablosistemas  Thank you! The quick response and help are highly appreciated.

**Comment by pablosistemas** [comment]
@Afindor Can I close this issue? If you need some additional help, please let me know to improve this work as good as possible.
